---
name: Enforce Pull Request has a valid gitmoji prefix
description: This action enforces that a pull request title contains a valid gitmoji prefix

inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get all Gitmoji's
      id: gitmojis
      shell: bash
      run: |
        curl -s https://gitmoji.dev/api/gitmojis | jq '.gitmojis[].emoji' > gitmojis.txt
        if [ ! -s gitmojis.txt ]; then
          echo "::error::Failed to fetch gitmojis from API"
          exit 1
        fi

    - name: Check if PR title has a valid gitmoji prefix
      id: check-gitmoji
      shell: bash
      run: |
        gitmojis=$(cat gitmojis.txt)
        gitmoji=$(echo "${{ github.event.pull_request.title }}" | cut -d ' ' -f1)
        if [[ ! $gitmojis == *"$gitmoji"* ]]; then
          echo "is_valid=false" >> $GITHUB_ENV
        else
          echo "is_valid=true" >> $GITHUB_ENV
        fi

    - name: Handle PR Comment
      shell: bash
      run: |
        if [ -z "${{ github.event.pull_request.number }}" ]; then
          echo "::error::No pull request number found. This action should only run on pull request events."
          exit 1
        fi

        PR_NUMBER="${{ github.event.pull_request.number }}"
        REPO_API_URL="https://api.github.com/repos/${{ github.repository }}"
        COMMENTS_URL="${REPO_API_URL}/issues/${PR_NUMBER}/comments"

        # Create comment content
        if [ "${{ env.is_valid }}" == "true" ]; then
          COMMENT_BODY="# gitmoji validation\n\n:white_check_mark: Valid gitmoji prefix in PR title."
        else
          COMMENT_BODY="# gitmoji validation\n\n:x: Invalid gitmoji prefix in PR title. Please use a valid gitmoji prefix."
        fi

        # Find existing comment
        EXISTING_COMMENT=$(curl -s -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" "${COMMENTS_URL}" | \
          jq -r '.[] | select(.body | startswith("# gitmoji validation")) | .url' | head -n1)

        # Update or create comment
        if [ -n "$EXISTING_COMMENT" ]; then
          curl -s -X PATCH \
            -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"${COMMENT_BODY}\"}" \
            "${EXISTING_COMMENT}"
        else
          curl -s -X POST \
            -H "Authorization: token ${{ inputs.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{\"body\":\"${COMMENT_BODY}\"}" \
            "${COMMENTS_URL}"
        fi

        # Exit with error if validation failed
        if [ "${{ env.is_valid }}" != "true" ]; then
          exit 1
        fi

branding:
  icon: "check-circle"
  color: "green"
